# Composer file for Tellicast Server and Clients
version: '3'

networks:
  # Basic Service network
  sat:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
  ter:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

 #driver: weaveworks/net-plugin:latest

services:
#
# Tellicast Server
  tc-server-bas:
    image: 'oespanyol/tellicast_tc-server-bas:latest'
    networks:
      - sat
    ports:
     - "10100:10100"
#
# Basic Service
  tc-client-bas:
    image: 'oespanyol/tellicast_tc-client-bas:latest'
    networks:
      - sat
    ports:
     - "8100:8100"
#
# Terrestrial-1
  tc-client-ter-1:
    image: 'oespanyol/tellicast_tc-client-ter-1:latest'
    networks:
      - ter
    ports:
     - "8500:8500"
