# Composer file for Tellicast Server and Clients
version: '3'

networks:
  # Basic Service network
  sat:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24
  ter:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

 #driver: weaveworks/net-plugin:latest

services:
#
# Tellicast Server
  tc-server-bas:
    build: 
      context: server/
      args:
       - service=bas
       - maddress=232.223.122.1:4711
       - mname=TSL-BAS
       - iaddress=172.19.0.2
    networks:
      sat:
        ipv4_address: 172.19.0.2
    ports:
     - "10100:10100"
#
# Basic Service
  tc-client-bas:
    build: 
      context: client/
      args:
       - service=bas
       - maddress=232.223.122.1:4711
       - iaddress=172.19.0.3
       - mname=TSL-BAS
       - username=ISRO-T
       - userkey=TESTKEY
    networks:
      sat:
        ipv4_address: 172.19.0.3
    ports:
     - "8100:8100"
#
# Terrestrial-1
  tc-client-ter-1:
    build: 
      context: client/
      args:
       - service=ter-1
       - maddress=232.223.122.3:4711
       - iaddress=172.20.0.3
       - mname=TSL-TER-1
       - username=ISRO-T
       - userkey=TESTKEY
    networks:
      ter:
        ipv4_address: 172.20.0.3
    ports:
     - "8500:8500"
